### ISSUE TITLE
Should there be another row to report on tests done?

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/status.keyman.com#153]
The current status tracks only three things:

1. issues created
2. PRs submitted
3. codes reviewed

<img width="213" alt="image" src="https://user-images.githubusercontent.com/28331388/133362765-76b122f9-61cc-429b-8353-9f08b1c0ff4d.png">

Can we have a forth one for `tests done`?

This would help tester(s) to collect what they've tested for report purposes.

**Comment by mcdurdin** [comment]
Great idea ... will have to think how it could be implemented (it's a little trickier than the other three...)
