### ISSUE TITLE
bug: author icons disappear after clicking any "view by" link

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#176]
It seems that author icons next to Keyman Status disappear if you click any of the "View by" links, and there's no way to get them back except reload (and even that does always help).

Initial:
![Screenshot from 2021-12-02 09-30-30](https://user-images.githubusercontent.com/181336/144386153-673f0731-602f-4445-8e8d-95e4df4abace.png)

After clicking the "View by" links:
![Screenshot from 2021-12-02 09-31-02](https://user-images.githubusercontent.com/181336/144386190-8fa83c5f-64de-4e47-b35e-b954d89e763f.png)

**Comment by mcdurdin** [comment]
Fixed by #177.
