### ISSUE TITLE
"Pending" status shows Unicode codepoint in Firefox on Linux

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#20]
When running in Firefox on Linux the "Pending" status shows a generic character with the Unicode point instead the yellow circle you get on Windows.
Chromium shows an empty rectangle - which still isn't the yellow circle but better :smile: 

![Screenshot from 2019-11-04 17-32-34](https://user-images.githubusercontent.com/181336/68138877-80bb2080-ff29-11e9-8315-9555c53d3b76.png)

**Comment by mcdurdin** [comment]
Okay, I'll put this as a dup of #21 because it's the same underlying issue 😁
