### ISSUE TITLE
bug: copying contributions data to clipboard no longer working

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/status.keyman.com#206]

**Comment by mcdurdin** [comment]
This seems to be working again. I am not sure who originally reported this (@ermshiperete?)

**Comment by ermshiperete** [comment]
It's still not working for me, both on Ubuntu 20.04 with Chrome 98.0.4758.102 nor on Windows 10 with Microsoft Edge 98.0.1108.56.

**Comment by mcdurdin** [comment]
Found the issue. [https vs http](https://web.dev/async-clipboard/#security-and-permissions)!

> As with many new APIs, the Clipboard API is only supported for pages served over HTTPS.

If you connect with http, you'll see `navigator.clipboard === undefined` on Edge. I'll see if I can force upgrade to https but in you can always do that manually yourself :grin:

**Comment by ermshiperete** [comment]
You mean it happens if I use http://status.keyman.com/ instead of https://status.keyman.com/?

Unfortunately, for me copying to the clipboard also doesn't work when using https://status.keyman.com/ (which I always have been using).

**Comment by mcdurdin** [comment]
Right, are you getting any error messages in Developer console? Are you sure you were using https://status.keyman.com/ on Edge? I was able to repro on Edge when I connected with http, but not when I connected with https. There may be other issues on Ubuntu of course...

**Comment by ermshiperete** [comment]
Yes, I'm sure that I use https://status.keyman.com. I don't get any output in Developer console.

I tried the sample on the [https vs http](https://web.dev/async-clipboard/#security-and-permissions) page and that works, so we must be doing something wrong. Two things I noticed: their sample waits for the answer; the other is that vscode shows a warning on `navigator.clipboard as Clipboard`: 

```
Conversion of type 'Clipboard' to type 'Clipboard' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'write' are incompatible.
    Type '(data: ClipboardItems) => Promise<void>' is not comparable to type '(items: [ClipboardItem]) => any'.
      Types of parameters 'data' and 'items' are incompatible.
        Type '[ClipboardItem]' is not comparable to type 'ClipboardItems'.
          Type 'ClipboardItem' is missing the following properties from type 'ClipboardItem': types, getTypets(2352)
```

**Comment by ermshiperete** [comment]
Interesting. Copying the branch name works (where `typeof this.text` is a string) which point to the warning in vscode.

Changing the definition for `Clipboard.write` to

```
write(items: ClipboardItem[]);
```

make vscode happy, but I can't test it locally, so don't know if it would make a difference.

**Comment by ermshiperete** [comment]
By the way, it seems that Firefox now supports the clipboard API since version 90. It requires manual settings in about:config:

- `dom.events.asyncClipboard.read` set to true
- `dom.events.asyncClipboard.clipboardItem` set to true

It's likely that these settings will change in a future version.

**Comment by mcdurdin** [comment]
> but I can't test it locally

See

**Comment by mcdurdin** [comment]
I _think_ that part of the issue here is that the clipboard copy can take a little time, and if you switch away, it doesn't complete the copy. So we need to add a spinner.
