### ISSUE TITLE
Status symbols not very obvious on Linux

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#21]
The status symbols show up differently when running on Linux:

Firefox on Linux:
![Screenshot from 2019-11-04 17-37-50](https://user-images.githubusercontent.com/181336/68139126-e14a5d80-ff29-11e9-9880-6411eceab561.png)

Chromium on Linux:
![Screenshot from 2019-11-04 17-38-26](https://user-images.githubusercontent.com/181336/68139160-f2936a00-ff29-11e9-9860-26101674239a.png)

Firefox on Windows:
![Windows](https://user-images.githubusercontent.com/181336/68139315-38e8c900-ff2a-11e9-9d45-95aea8acbe8b.png)

**Comment by mcdurdin** [comment]
Sorry :( emoji support on Linux is a bit behind? I could replace with images but more work ... :) Or you could upgrade to Windows or macOS?

**Comment by ermshiperete** [comment]
Thanks for the hint! Ubuntu uses Google's _Noto Color Emoji_ font and that doesn't include the emojis added in the latest Unicode version(s). As a workaround I copied the `seg*.ttf` fonts from my Windows machine, and with that the symbols show as expected.
