### ISSUE TITLE
build for linux is broken when clicking on "linux.lsdev.sil.org" from the "v" icon

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/status.keyman.com#250]
The link in question: http://linux.lsdev.sil.org/ubuntu/pool/main/k/keyman/

What's clicked on:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/28331388/165046248-d0b65ee9-e9e8-4702-b036-cc729a80bca5.png">

The error message on the page visited:
<img width="797" alt="Screen Shot 2022-04-25 at 3 00 25 PM" src="https://user-images.githubusercontent.com/28331388/165046350-d435aa58-5940-4449-95ce-abf6304b1c29.png">

**Comment by ermshiperete** [comment]
Unfortunately that link (or any other link to list the available packages) no longer works since they changed the llso server.

**Comment by ermshiperete** [comment]
LTOps doesn't plan to re-enable the directory listing for llso so that link won't work again. If we want to have a page where it's possible to download the Linux packages, we'd have to create our own page, based on the package names, version and distributions. The packages are available as https://s3.console.aws.amazon.com/s3/object/linux.lsdev.sil.org?region=us-east-1&prefix=ubuntu/pool/main/k/keyman/ibus-keyman_15.0.239-1%2Bjammy1_amd64.deb.

Alternatively we could remove the link.

**Comment by mcdurdin** [comment]
> Unfortunately that link (or any other link to list the available packages) no longer works since they changed the llso server. Cf. https://sil-language-software.slack.com/archives/C9S138H28/p1643100569007200

That link no longer appears to be available (outside the Slack 10,000 memory?)

> The packages are available as https://s3.console.aws.amazon.com/s3/object/linux.lsdev.sil.org?region=us-east-1&prefix=ubuntu/pool/main/k/keyman/ibus-keyman_15.0.239-1%2Bjammy1_amd64.deb.

Is this the only file needed? If so we can build that URL easily enough in status.keyman.com.

**Comment by ermshiperete** [comment]
The conversation from Slack:

[eberhard](https://app.slack.com/team/U5E8URE14)
 [Jan 25th at 09:49](https://sil-language-software.slack.com/archives/C9S138H28/p1643100569007200)
Would it be possible to re-enable a way to list the available packages on llso, something like https://linux.lsdev.sil.org/ubuntu/?prefix=ubuntu/pool/main/k/keyman-config/ or http://linux.lsdev.sil.org/ubuntu/pool/main/k/ ? I find that often helpful in troubleshooting.
4 replies
[Greg Mackay](https://app.slack.com/team/UGHL3VCQ5)
  [6 months ago](https://sil-language-software.slack.com/archives/C9S138H28/p1643122081007300?thread_ts=1643100569.007200&cid=C9S138H28)
I see how this is being done on [packages.sil.org](http://packages.sil.org/), but let me confirm with Mark S first before I configure that.  I'm not sure if this was left out for a reason.
[eberhard](https://app.slack.com/team/U5E8URE14)
  [3 months ago](https://sil-language-software.slack.com/archives/C9S138H28/p1650875264245609?thread_ts=1643100569.007200&cid=C9S138H28)
[@Greg Mackay](https://sil-language-software.slack.com/team/UGHL3VCQ5)
Any updates on this? :smiley:
[Greg Mackay](https://app.slack.com/team/UGHL3VCQ5)
  [3 months ago](https://sil-language-software.slack.com/archives/C9S138H28/p1650889172108569?thread_ts=1643100569.007200&cid=C9S138H28)
Wow, I guess this one fell through the cracks.  Sorry about that.
Or is  this the one that we created an AWS account for you, so you could view this?  Maybe I have this confused with another request.
[eberhard](https://app.slack.com/team/U5E8URE14)
  [3 months ago](https://sil-language-software.slack.com/archives/C9S138H28/p1650961214227429?thread_ts=1643100569.007200&cid=C9S138H28)
ahh, that's right. I remember now :smiley:
