### ISSUE TITLE
The PR fixes a Keyman Developer issue, yet the build to be downloaded doesn't show up in the Artifact section

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/status.keyman.com#276]
The PR keymanapp/keyman#6848 fixes a Keyman Developer issue, yet the build to be downloaded doesn't show up in the Artifact section under the `User Test Results` section, it however does get shown in TeamCity

| Where from | Screenshots |
| --- | --- |
| In the PR | In TeamCity |
| <img width="400" alt="image" src="https://user-images.githubusercontent.com/28331388/176136092-84566386-0788-480c-9ba4-f26dd2f9843a.png"> | <img width="400" alt="image" src="https://user-images.githubusercontent.com/28331388/176136382-24ad4d0e-b9d9-4339-a460-372016fd2206.png"> |

It would be more helpful to have it down right under the `User Test Results` section.

**Comment by mcdurdin** [comment]
This is due to the move of Keyman Developer from /windows/src/developer to /developer/src which is pending in keymanapp/keyman#6630. It will self-resolve once that is merged.
