### ISSUE TITLE
bug(testbot): Bot doesn't ignore tests which are commented out

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#284]
If you write a test but then comment that out, the test won't show up in the GitHub description, but it will still show up with the testbot.

Example:

```
<!--
- **TEST**: this test is commented and shouldn't show  up
-->
```

**Comment by mcdurdin** [comment]
OK, I am not going to try and fix this by parsing out HTML comments -- it'd be a hassle to do in the current bot model. Instead, I am going to suggest you work around it by changing the test text as to:

```
<!--
- **DISABLED-TEST**: this test is commented and shouldn't show  up
-->
```

You can leave the comment or not, as you like. :grin: Sorry!
