### ISSUE TITLE
bug:  high-level retest command breaks test-bot

### ISSUE THREAD

**Issue by jahorton** [keymanapp/status.keyman.com#292]
This issue occurred for https://github.com/keymanapp/keyman/pull/7343.

Noting the documentation about test-bot commands here:  https://github.com/keymanapp/keyman/wiki/User-Testing-Workflows#retesting

[This comment](https://github.com/keymanapp/keyman/pull/7343#issuecomment-1262999510) originally tried to use a `retest GROUP_IOS`, with no further specification - with the goal of re-running all iOS tests.

The test bot appeared to simply ignore it.  So, I made a second comment further down that repeated the retest command but also enumerated each test.  _**Again**_, the test bot appeared to ignore _that_.

It was only when I edited the original comment (and, admittedly, I deleted the second comment first) to enumerate the tests that test-bot started working on that PR again.

**Comment by mcdurdin** [comment]
Looks like there have been a few glitches in webhook deliveries (perhaps network related?) so that may have had an impact.

`@keymanapp-test-bot retest GROUP_IOS` should have worked, so will check that.

**Comment by mcdurdin** [comment]
The correct incantation is `@keymanapp-test-bot retest GROUP_IOS all` -- the `all` is not currently optional in this case. Workin' on that!

**Comment by jahorton** [comment]
Ah.  Yeah, I was too worried it'd function more like our builder's specification:  adding new entries never narrows scope and only expands it.  Based on that paradigm, the "all" would say to retest everything, making the `GROUP_IOS` part redundant.
