### ISSUE TITLE
bug: Current doesn't show issues if all issues have PRs

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#342]
If all issues assigned to a sprint have PRs and the "All" view is selected, the sprint shows up as with e.g. `0 (1)`:

![Screenshot from 2023-02-06 17-03-56](https://user-images.githubusercontent.com/181336/217023202-317bb247-1f3a-4b45-97b7-969245d94afb.png)

However, if the "Current" view is selected, the sprint no longer shows up even though the PRs are still open:
 
![Screenshot from 2023-02-06 17-04-15](https://user-images.githubusercontent.com/181336/217023321-7ea6f8ba-f18d-4af5-b368-c4217337a618.png)

**Comment by mcdurdin** [comment]
This is actually intentional -- the idea being that issues that have PRs assigned to close them are 'done'.

**Comment by ermshiperete** [comment]
I agree with the "0 (1)" notation, but until the PR is merged I don't consider it really "done" - there's still work to be done. Ideally this is just pressing the Merge button, but it could be quite a bit more resulting from code reviews or user test failures.

**Comment by mcdurdin** [comment]
Sure -- but I am trying to reduce the noise in the view, because we still have the PR on the right hand side for tracking. The issue only disappears if the PR is going to auto-close it on merge. Does that work or do you want to see `0 (1)`?
