### ISSUE TITLE
chore: issues created through Sentry are not counted as contributions

### ISSUE THREAD

**Issue by jahorton** [keymanapp/status.keyman.com#402]
See: https://github.com/keymanapp/keyman/issues/10136.

Contrast:

![image](https://github.com/keymanapp/status.keyman.com/assets/25213402/1fc3494f-5413-4e31-9f59-d60f511e23a9)

If it were counted as my contribution, https://github.com/keymanapp/keyman/issues/10136 would be included in my "issues" list for "Tue Dec 5".

Granted, such issues are generally "posted" _by_ the `sentry-io` bot, mechanically speaking, so there's nobody _implicitly_ connected to the issue.  It's a reasonable limitation, so I get why I status.keyman.com doesn't automatically "connect the dots."

That said, if one of us links ourselves or mentions ourselves (first) in the issue description, it'd be nice to have that counted in our contributions list.

**Comment by mcdurdin** [comment]
it'd be nice but we don't currently read the issue description because it's too expensive, so sorry, this one is a wontfix :)
