### ISSUE TITLE
bug: Unassigned issues tab doesn't toggle

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#433]
For most tabs it's possible to click on a team member to show his assigned issues and contributions, and to click the team member again to get back to the main view.

For the red question mark with the Unassigned Issues it's possible to click to show the unassigned issues, but clicking again doesn't do anything. Would be helpful if that would toggle as well.

**Comment by mcdurdin** [comment]
I also note that the refresh is not remembering which tab was active, will fix at same time.
