### ISSUE TITLE
bug: clipboard support issues on macOS Firefox

### ISSUE THREAD

**Issue by jahorton** [keymanapp/status.keyman.com#58]
Attempting to use the feature introduced in #55 with macOS Firefox did not result in the HTML-formatted text being copied to the clipboard.

This issue did not occur in Chrome on the same OS.

**Comment by mcdurdin** [comment]
Sadly, FireFox [does not support](https://caniuse.com/?search=clipboard) `ClipboardItem` which we need for HTML formatting.

**Comment by ermshiperete** [comment]
See also https://github.com/keymanapp/status.keyman.com/issues/206#issuecomment-1050221878
