### ISSUE TITLE
Add onboard-keyman repo

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#60]
Might be good if [onboard-keyman](https://github.com/keymanapp/onboard-keyman) repo would show up in the status.

**Comment by mcdurdin** [comment]
I've avoided adding dependency repos which are not our primary focus, such as onboard-keyman, sentry-native, tavultesoft.com, CEF4Delphi_binary, CEF4Delphi, ldml-keyboards, blog.tavultsoft.com, and even keyman-tools. I just moved the one issue opened on that repository across to the keyman repo and disabled issues on the onboard-keyman repo.

I don't think we have room on the dashboard for all these additional repos which are also normally very quiet. I think perhaps we just go ahead without them...
