### ISSUE TITLE
feat: Add build monitors and deployment monitors for Jenkins etc

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/status.keyman.com#63]
Would it be possible to add build monitors for Jenkins to status.keyman.com? I think it might be possible to have a new 'deployment' icon between the build version and the test icon; we might do a similar thing for Android and iOS to bubble their status up as well.Can we discuss what this would look like? 
> Thanks! Good idea. However, I think it would be better and easier to check what package version we have on llso.

>> Have both is better yet -- shows us clearly when there is a discrepancy between build and release.

> Instead of adding a new icon we could change the "download V": instead of being a link to download.keyman.com we could change it to a pop up (similar to what we have for the issues). The pop up would have links to download.keyman.com, llso (and the ppa if we automatically upload) and show the version of each.

(via email with @ermshiperete)

**Comment by mcdurdin** [comment]
per @ermshiperete:

I guess we can use a URL similar to https://jenkins.lsdev.sil.org/view/Keyman/view/Pipeline/job/pipeline-keyman-packaging/job/master/lastBuild/api/json. The returned json has a result field. I'm not sure if lastBuild or lastCompletedBuild is better. Also, this requires authentication.

https://stackoverflow.com/questions/18238616/jenkins-get-last-completed-build-status

As link from status.keyman.com we can use https://jenkins.lsdev.sil.org/blue/organizations/jenkins/pipeline-keyman-packaging/detail/master/1430/pipeline/ (with 1430 being the build number we get from json)

**Comment by ermshiperete** [comment]
Since we no longer create packages on Jenkins we can close this issue.
