### ISSUE TITLE
bug: New Linux bug doesn't show up on status page

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/status.keyman.com#96]
This morning I created  a new Linux bug ([#4798](https://github.com/keymanapp/keyman/issues/4798)), but as of this afternoon it doesn't show up on the status page: not under the Linux issues nor does it show up as issue that I created.

**Comment by ermshiperete** [comment]
Nor does this issue show up :disappointed:

**Comment by ermshiperete** [comment]
And #94 still shows up on the status page although it's already closed.

**Comment by mcdurdin** [comment]
Yep the webhook from github was disabled and pointing to the wrong endpoint -- my mistake when moving to the live site...
